### ISSUE TITLE
Terminating due to error receiving QTM parameters: string indices must be integers

### ISSUE THREAD

**Issue by cafeciaojoe** [qualisys/crazyflie-resources#1]
Getting the following error when trying to run example-simple-hover.py:

~ Qualisys x CrazyFlie ~                                                                                                
Connecting to radio://0/80/2M                                                                                           
Connected to QTM, version Version set to 1.17                                                                           
Getting parameters from QTM...                                                                                          
Starting to record new measurement in QTM...                                                                            
Starting listening to QTM packet stream...                                                                              
Found 1 6DoF bodies defined in QTM project:                                                                             Terminating due to error receiving QTM parameters: string indices must be integers

Windows 10 with Anaconda3, using QTM 1.0.1, cflib 0.1.6, xmltodict 0.11.0

We're able to establish a connection to the aircraft using the crazyflie PC client, so there's no problem with the radio or the aircraft.

If we modify line:

qtmRigidbodies_idxByName[body['Name']] = i

to read:

qtmRigidbodies_idxByName[body] = i

we get the error:

Got link error callback [Too many packets lost] in state [1]                                                            Connection to radio://0/80/2M failed: Too many packets lost                                                             Terminating due to error while initializing flight controller: Too many packets lost

Any idea on how to fix this?

Cheers

**Comment by mbaytas** [comment]
When you run the script, do you have a 6DOF body configured in QTM to track the Crazyflie, and is it named "Crazyflie"? Is it placed correctly, per the instructions in the repo README?

Could you please print out what the variables `bodies_info` and `bodies` contain right after the line `bodies = bodies_info['Body']` is executed, and paste it here?

**Comment by cafeciaojoe** [comment]
Hi, I added the full radio address (//0/80/2M/A0A0A0A0A0) and managed to get past the error message I received before. The drone to attempt to take off, it took off uncontrollably and crashed. 

I have a different issue now. Which I will raise separately to keep things clean.
